name = "newsnow"
type = "javascript"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "35e0e930-ae7f-4a55-a95a-76aa800be221"
